name: CI Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: build-gradle
        run: ./gradlew build test install --build-cache --scan -s
      - name: Archive build results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ${{ runner.os }}-build-${{ github.sha }}
          path: build
#      - name: integration-test
#        if: runner.os != 'Windows'
#        run: |
#          export PATH=`pwd`/build/install/muleflowdiagrams/bin:$PATH
#          cd itests
#          ./tests.sh
  testing:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8,11,13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/download-artifact@v1
        with:
          name: ${{ runner.os }}-build-${{ github.sha }}
          path: build
      - run: |
          java -version
          chmod +x ./build/install/muleflowdiagrams/bin/muleflowdiagrams
          ./build/install/jbang/bin/muleflowdiagrams --version